name: nightly build

on:
  push:
    branches:
      - main

permissions:
  contents: write

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  nightly-build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up QEMU
        uses: docker/setup-qemu-action@master
        with:
          platforms: all
      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@master
      - name: Install earthly
        uses: earthly/actions-setup@v1
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          version: "latest"
          use-cache: true
      - name: Build artifacts
        run: |
          set -x
          earthly --ci --output +release \
            --VERSION=nightly
      - name: Build FIPS artifacts
        run: |
          set -x
          earthly --ci --output +release-fips \
            --VERSION=nightly \
            --SPECTRO_PUB_REPO=us-docker.pkg.dev/palette-images-fips
      - name: Upload release artifacts
        env:
          GH_TOKEN: ${{ github.token }}
        run: |
          gh release upload --clobber nightly build/*
